
export const _GM_TABLE_SCROLL_X_CONTAINER_ = '_GM_TABLE_SCROLL_Y_CONTAINER_'

export const _GM_TABLE_SCROLL_Y_CONTAINER_ = '_GM_TABLE_SCROLL_Y_CONTAINER_'

export const _GM_TABLE_SCROLL_CELL_PREFIX_ = '_GM_TABLE_SCROLL_CELL_PREFIX_'